security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512
  role_hierarchy:
    ROLE_USER:        ROLE_USER
    ROLE_ADMIN:       ROLE_ADMIN
    ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
  providers:
    fos_userbundle:
      id: fos_user.user_provider.username
    in_memory:
      memory: ~
  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: fos_userbundle
        csrf_provider: form.csrf_provider
      logout: true
      anonymous: true
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      anonymous: ~
  access_control:
    - { path: ^/offer$, role: ROLE_USER }
    - { path: ^/offer/, role: ROLE_USER }
    - { path: ^/post_create$, role: ROLE_USER }
    - { path: ^/post_create/$, role: ROLE_USER }
    - { path: ^/geo_create$, role: ROLE_USER }
    - { path: ^/geo_create/$, role: ROLE_USER }
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/admin$, roles: ROLE_ADMIN }
